management.endpoints.web.exposure.include: "*"

spring:
  application:
    name: spring-boot-config
  config:
    import: configserver:http://localhost:8888/

#  profiles:
#    active: test
#    include: included