/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ir.darkdeveloper;

import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
    }
}
