server:
  port: 7003
logging:
  level:
    root: info
    ir.darkdeveloper.microservice: debug


server.error.include-message: always

# Strongly recommend to set this property to "none" in a production environment!
spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:mysql://localhost/review-db
  username: user
  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000


---
spring.config.activate.on-profile: docker
server.port: 8080

spring.datasource:
  url: jdbc:mysql://mysql/review-db