server:
  port: 7003
logging:
  level:
    root: info
    ir.darkdeveloper.microservice: debug


server.error.include-message: always

# Strongly recommend setting this property to "none" in a production environment!
spring.jpa.hibernate.ddl-auto: update

#spring.datasource:
#  url: jdbc:mysql://localhost/review-db
#  username: user
#  password: pwd

#spring.datasource.hikari.initializationFailTimeout: 60000

spring:
  r2dbc:
    url: r2dbc:mysql://localhost/review_service
    password: 1234
    username: darkdeveloper



---
spring.config.activate.on-profile: docker
server.port: 8080

spring:
  r2dbc:
    url: r2dbc:mysql://localhost/review-db
